### ISSUE TITLE
Sonoff 4CH PRO R2 string?

### ISSUE THREAD

**Issue by milonet** [RavenSystem/esp-homekit-devices#520] opened 2019-10-02 08:35 UTC
Hi, @RavenSystem  the string for 4CH in "HAA Templates" section is compatible with 4CH pro R2 ?

**Comment by milonet** [comment] 2019-10-02 19:51
An update: If i put the sonoff in setup mode pressing 10 time a physical button, it connect to my wifi home. When i click on save to update wifi home settings, the sonoff becomes unavailable until put in setup mode. It seem that keep the wifi settings only in setup mode..

**Comment by RavenSystem** [comment] 2019-10-13 22:54
I don’t know. Try it and comment, please.

**Comment by milonet** [comment] 2019-10-19 16:24
Hi, i tried this string: `{
  "c": {
    "l": 13,
    "i": 1,
    "b": [
      {
        "g": 0,
        "t": 5
      }
    ]
  },
  "a": [
    {
      "t":4,"0": {
        "r": [
          {
            "g": 12,
			"i":0.4,
			"v":1
		
          }
        ]
      },
      "1": {
        "r": [
          {
            "g": 12
          }
        ]
      },
      "b": [
        {
          "g": 0
        }
      ]
    },
    {
      "t":4,"0": {
        "r": [
          {
            "g": 5,
			"i":0.4,
			"v":1
          }
        ]
      },
      "1": {
        "r": [
          {
            "g": 5
          }
        ]
      },
      "b": [
        {
          "g": 9
        }
      ]
    },
    {
      "0": {
        "r": [
          {
            "g": 4
          }
        ]
      },
      "1": {
        "r": [
          {
            "g": 4,
            "v": 1
          }
        ]
      },
      "b": [
        {
          "g": 10
        }
      ]
    },
    {
      "0": {
        "r": [
          {
            "g": 15
          }
        ]
      },
      "1": {
        "r": [
          {
            "g": 15,
            "v": 1
          }
        ]
      },
      "b": [
        {
          "g": 14
        }
      ]
    }
  ]
}` 
do you confirm that is good?
I have two problem:
1) When device power on the relay on button 0 inching .. this is not good because i will connect the relay to lock mechanism
2) the devices exit from wifi. the only way to reach it on HOME (non captive portale) wifi network is putting on setup mode. After save the string

**Comment by RavenSystem** [comment] 2019-10-19 17:44
1. When device power on, the relay in GPIO 12 should be low (value:0, off...). Please, include "o":1 in config section and send the log. I don't see any relay activation at boot; all relays are off.

2. Yes, the issue is fixed with the newest version 0.3.3 I have released just now. (Tested with your JSON).

**Comment by milonet** [comment] 2019-10-19 23:34
Hi, thak you for you support. Much appreciated.
The wifi issue is fixed, the device still reachable after JSON uploaded.
But anoter problem is born. It's impossible to enter in setup mode. I press for 10-11 seconds the button 0 after device start (the led blink correctly) but i cannot enter in web page.
In your test does it work correctly?

**Comment by milonet** [comment] 2019-10-19 23:34
...and... how I can see the boot logs?

**Comment by milonet** [comment] 2019-10-20 00:38
Hi, i tested with success this JSON string: `{"c":{"l":13,"i":1,"b":[{"g":0,"t":5}]},"a":[{"t":4,"i":0.4,"0":{"r":[{"g":12,"v":1}]},"1":{"r":[{"g":12,"v":0}]},"b":[{"g":0}]},{"t":4,"i":0.4,"0":{"r":[{"g":5,"v":1}]},"1":{"r":[{"g":5,"v":0}]},"b":[{"g":9}]},{"0":{"r":[{"g":4}]},"1":{"r":[{"g":4,"v":1}]},"b":[{"g":10}]},{"0":{"r":[{"g":15}]},"1":{"r":[{"g":15,"v":1}]},"b":[{"g":14}]}]}`

The problem of initial inching on boot devices seems solved. WiFi after JSON setting is ok.
For me 0.3.3 is stable !!

**Closed** 2019-10-20 17:10 UTC
Labels: HAA
