### ISSUE TITLE
Control devices trought Siri on iOS 14.b2 don't work

### ISSUE THREAD

**Issue by Chuck3CZ** [RavenSystem/esp-homekit-devices#1043] opened 2020-07-12 19:09 UTC
I dont know if it is issue of iOS 14.b2 or HAA/RC, but not certified **EIIE rev-1 works** on this newer iOS, trought Siri, but **HAA 0.9.2-2.5.1 doesn't**

**Comment by camilogrifi** [comment] 2020-07-18 05:30
I have this problem!!! :(

**Comment by PEA71** [comment] 2020-07-18 12:43
Same issue for me. Let's see if this issue persist over next beta (probably next week).

**Comment by PEA71** [comment] 2020-07-23 20:43
Issue not resolved with beta 3...
If I try to do a Save with the "Controller" app, it seems that it cannot read the information of HAA devices. But not sure if it's linked. ![image](https://user-images.githubusercontent.com/62342800/88336768-dd6b9f00-cd35-11ea-991f-6c46b4e402a9.jpeg)

**Comment by peros550** [comment] 2020-07-24 08:04
hi guys, I can confirm the issue on beta 3. Also, I'm aware that similar issues exist for accessories brought to Homekit through Home Assistant hub. 
Interestingly, I do still have a sonoff mini which I never bothered to open it and install HAA. I'm using it though this homebridge plugin. This one seems to be controlled by Siri with no issues on ios14b3.

**Comment by pkordal** [comment] 2020-07-25 12:15
Same here. It works well for original devices like Hue or Aqara or even homebridge but not for devices with HAA.

**Comment by peros550** [comment] 2020-07-25 13:22
Question is : what HomeBridge does and Siri works with it

**Comment by Chuck3CZ** [comment] 2020-07-27 11:32
Homebridge Works, TimeThinker socket works well too (EIIE), only on HAA Siri says - not found.

**Comment by PEA71** [comment] 2020-08-06 18:46
Issue is still present with iOS 14 beta 4. 
I have an older iPad with iOS 12.4.8 and everything is working as normal. 
There probably a little change under the hood in iOS 14 that cause this issue...

**Comment by angyalZK** [comment] 2020-08-06 20:48
Issue still on iOS 13.6. Sometimes Siri can switch on the light, but can't switch off. Or says "done" but does nothing.

**Comment by Murdrock** [comment] 2020-08-18 20:25
Anyone tried beta 5 !?

**Comment by Chuck3CZ** [comment] 2020-08-18 20:31
Reported to Apple with Siri debug profile, they asked for it, and now it works, closing issue😍🙌🥰✅✅✅

**Closed** 2020-08-18 20:31 UTC

**Comment by PEA71** [comment] 2020-08-26 18:08
I confirm! All work as expected with Siri now! Thanks @Chuck3CZ !
👍🍻
