### ISSUE TITLE
0.5.8 toggle fail?

### ISSUE THREAD

**Issue by Manelvallsvila** [RavenSystem/esp-homekit-devices#174] opened 2019-01-08 18:10 UTC
Hi Jose,

Thanks in advance for the good job you are doing!

Since last Update to 0.5.8, on a sonoff basic, the mode 2 toggle doesn't work with the Wall switch. I have a classic sonoff board with Wall switch conected to GND and gpio14.

Question:
Is it posible to be a software problema? I have this unit in Wall...

Another question:
Every time you reléase a new firmware versión , I flash it OTA, but I don't know if it is necessary or if it's not.
How can I know what changes you implement in new versions to know if its needed to flash or an option?

Muchas gracias!

**Comment by RavenSystem** [comment] 2019-01-11 17:18
Can you post your custom settings from EVE?

What you mean when say "I flash it OTA"??

FYI: Changelogs are here: https://github.com/RavenSystem/esp-homekit-devices/releases

**Comment by macjl** [comment] 2019-01-11 18:31
Same issue here. With this settings, a button between GPIO2 and GND doesn't change the switch state on a Sonoff Basic: 
- Board Type : 2
- Device Type : 1
- External Toggle : 1
- Init State SW1 : 0

**Comment by Manelvallsvila** [comment] 2019-01-12 10:09
My custom settings feom EVE are:

Board Type: 1
Device type: 1
extermal toggle 1: 2
Init state SW1: 0

**Comment by RavenSystem** [comment] 2019-01-12 18:38
I will test it asap.

**Comment by RavenSystem** [comment] 2019-01-12 18:45
@macjl there is a bug with button mode (external toggle 1 = 1). It will be fixed with next update. 

@Manelvallsvila I need some testing to know where is the issue with extertal toggle 1 = 2, because it must work.

**Comment by RavenSystem** [comment] 2019-01-12 20:57
@Manelvallsvila Sorry, I can not reproduce your issue.

**Comment by RavenSystem** [comment] 2019-01-13 11:18
@seritos What you mean exactly? When external switch is ON (using External toggle: 2), Sonoff doesn't boot?

**Comment by seritos** [comment] 2019-01-13 12:16
If any of these two switches is pressed before the sonoff has power, then the sonoff wont boot/start once you power it up.
I discover it yesterday. I was doing some test and had to disable the mains from home to operate safely. Once finished, realized that some of the Sonoff where unresponsive. 
Then I relized why.

**Comment by RavenSystem** [comment] 2019-01-13 12:37
@seritos Confirmed! If GPIO2 is low (connected to GND), device doesn't boot anything. It's a hardware "issue" and can not be solved with code.

For an ESP module to boot up into normal run mode then the pins must be:
- GPIO0 = high
- GPIO2 = high
- GPIO15 = low

https://www.esp8266.com/viewtopic.php?t=18550

**Comment by RavenSystem** [comment] 2019-01-13 12:45
@seritos I think the best way to fix is replacing your Sonoff Basic with an old version, or a Shelly1.

**Comment by seritos** [comment] 2019-01-13 18:08
Oh, what a pity. 

I will try to solder it directly to the chip then.

Thanx!

**Comment by RavenSystem** [comment] 2019-01-27 20:35
@seritos Version 0.6.0 has a new board type 4, and you can attach your external toggle to GPIO3/RX pin.

**Closed by RavenSystem** 2019-01-27 20:35 UTC
