### ISSUE TITLE
"Close Garage door" in Siri command doesn't energize relay 

### ISSUE THREAD

**Issue by GPL71** [RavenSystem/esp-homekit-devices#229] opened 2019-02-03 09:32 UTC
This the environment
- Garage door device type in ravencore
- SONOFF SV board and dry contact
- Gate instead a garage door
  One shot on the button (of RF) and the gate open and it remain completely opened until another shot
  One shot on the button (of RF) and the gate start for the closing position 
  
Now...
If I say "Hey Siri Open garage door (or open gate)" all working fine and relay turns ON 
The gate starts opening.

When the gate is completely opened if I say "Hey Siri Close garage door (or close gate) the relay doesn't turn ON.
But if I say again "Hey Siri Open garage door (or open gate)" then relay turns ON and gate starts closing.
Siri say "gate is opening"

@RavenSystem Is there a way to avoid it?
Thank you for this firmware!!!!!

**Comment by RavenSystem** [comment] 2019-02-03 19:48
Maybe it is a bug. Screenshot of your EVE settings, please. I am going to test by myself.

**Comment by RavenSystem** [comment] 2019-02-04 11:06
I don’t understand. Screenshot goes away...

**Comment by RavenSystem** [comment] 2019-02-06 19:51
@GPL71 Not enough free time to test yet.

**Comment by RavenSystem** [comment] 2019-02-25 20:31
I don't see sensor close NC in your setup, so I have tested this bug with "sensor close NC = 0" and all of your settings. I can not reproduce the issue. In my case, Siri always works fine. Maybe the issue is caused by a wrong value of  "sensor close NC". Try setting it to 1 if you use 0, or set it to 0 if you actually use 1.

**Comment by GPL71** [comment] 2019-02-25 21:14
@RavenSystem 
Has opened sensor --->not is present in EVE
Sensor close NC ---> not is present in EVE

Can you tell me how to resolve or can you post the screenshot of your eve?

Thank you

**Comment by RavenSystem** [comment] 2019-02-25 21:35
@GPL71 "Has opened sensor" and "Sensor open NC" are both replaced with "Sensor open". But" Sensor close NC" must be present.

![img_0801](https://user-images.githubusercontent.com/8655274/53370251-8f3e4a80-394d-11e9-95c9-a5b0f8962a30.png)

**Comment by RavenSystem** [comment] 2019-02-25 21:45
I have updated" Sensor close NC" info in Wiki just now (It was outdated):
https://github.com/RavenSystem/esp-homekit-devices/wiki/RavenCore#sensor-close-nc-default-0

**Comment by dvelardi** [comment] 2019-02-26 19:12
You can explain better the issue?

I don’t home if it’s the same issue of my case: when I send open command, Apple home app show garage door always in opening state and if I ask Siri which it’s the state of garage door, Siri say don’t know...

DV
3389305149<tel:3389305149>

link - PRIVACY POLICY. http://www.meadinformatica.it/privacy/

Il giorno 25 feb 2019, alle ore 22:45, José A. Jiménez <notifications@github.com<mailto:notifications@github.com>> ha scritto:


I have updated" Sensor close NC" info in Wiki just now (It was outdated):
https://github.com/RavenSystem/esp-homekit-devices/wiki/RavenCore#sensor-close-nc-default-0<https://hes32-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fRavenSystem%2fesp%2dhomekit%2ddevices%2fwiki%2fRavenCore%23sensor%2dclose%2dnc%2ddefault%2d0&umid=9a17b87a-e5fc-4484-a54c-f678a8c1ab54&auth=48278bb8638c59b19e6a5c9ee0648ca7e9c732c1-38f23230befdbc9d1f344a04ad4c4de76b8f1bd7>

**Comment by GPL71** [comment] 2019-02-27 11:47
@RavenSystem I did your setup and changed the sensor to 1, but problem not was solved.
I have same issues on 4 different boards.
Any suggestion?

**Comment by GPL71** [comment] 2019-02-27 22:30
@RavenSystem this is configuration on all of 4 boards and I confirm the bugs again ... what's difference from your setup? Thank you
 
![schermata 2019-02-27 alle 23 26 10](https://user-images.githubusercontent.com/34108470/53527498-6e116180-3ae7-11e9-9700-f4deadf9b0e8.png)
![schermata 2019-02-27 alle 23 26 53](https://user-images.githubusercontent.com/34108470/53527509-74074280-3ae7-11e9-81d0-da74523a9559.png)
![schermata 2019-02-27 alle 23 27 34](https://user-images.githubusercontent.com/34108470/53527513-79fd2380-3ae7-11e9-95ce-b49104f8f496.png)
![schermata 2019-02-27 alle 23 28 02](https://user-images.githubusercontent.com/34108470/53527523-7f5a6e00-3ae7-11e9-8d2c-f5cf0cf559c9.png)

**Comment by RavenSystem** [comment] 2019-02-28 11:22
Bug found. Incompatible types int8 and bool.

**Comment by pilot1981** [comment] 2019-02-28 11:23
Incompatible only with SONOFF SV or also with SONOFF BASIC?

DV

**Comment by RavenSystem** [comment] 2019-02-28 19:14
Fixed in 0.6.2.

**Closed by RavenSystem** 2019-02-28 19:14 UTC
Labels: bug
